### ISSUE TITLE
ctrl-c退出后mpg123没有退出

### ISSUE THREAD

**Issue by JoeyZhu** [ma6174/fmpi#2]
mpg123cpu占用率好高啊。

**Comment by ma6174** [comment]
mpg123是用来将mp3格式转换为wav格式，以便以便使用fmpi进行广播，转码是比较耗费CPU的。
ctrl c后mpg123没有退出，那fmpi有退出吗？是不是转码卡住了？尝试一下

```
kill -9 `pidof mpg123`
```

**Comment by JoeyZhu** [comment]
就那一次没有退出，后来我试了几次都正常退出了。还有个问题是好些歌曲没有声音，而且按q也没有换到下一首啊

在 2014年7月26日 上午9:13，Ma Weiwei notifications@github.com写道：

**Comment by ma6174** [comment]
@JoeyZhu  这个问题可以看一下日志是否找到了歌曲，找到的歌曲能否转码和播放
